### ISSUE TITLE
IWebElement GetAttribute() method doesn't work

### ISSUE THREAD

**Issue by eazakli** [appium/appium-dotnet-driver#266]
## Description
C# codes, GetAttribute() method doesn't work and it gives an error. 
Please describe the issue. It may be a bug description. So then please briefly descride steps which you were trying to perform and what happened instead.
If there is the feature you want to see added to Appium .NET client so please describe necessity of this feature and the way that it should work.

## Environment

* .NET client build version or git revision if you use some shapshot:
* Appium server version or git revision if you use some shapshot: Appium Desktop v1.7.1
* Desktop OS/version used to run Appium if necessary: Windows 10 Enterprise
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: Node.js v8.12.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: Real Device Sony Xperia XZ1 
* IDE: VisualStudio 2017 Enterprise and C#
* Appium WebDriver 4.0.0.3-beta
* Selenium.WebDriver 3.14.0

## Details
GetAttribute() method doesn't work (Android Mobile Web Testing). I have tried for different attributes but it gives the same error.
Please provide more details, if necessary.

## Code To Reproduce Issue [ Good To Have ]
IWebElement info = driver.FindElement(By.CssSelector("div[class='pnr-status'] span"));
string abc=info.GetAttribute("text");

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.
You can git clone https://github.com/appium/sample-code or https://github.com/appium/sample-code/tree/master/sample-code/apps and reproduce an issue using C# and sample apps.
Also you can create a [gist](https://gist.github.com) with pasted C# code sample or put it here using markdown. About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and 
[Writing on GitHub](https://help.github.com/categories/writing-on-github/)

## Ecxeption stacktraces
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
   at OpenQA.Selenium.Appium.AppiumWebElement.<>c__DisplayClass21_0.<GetAttribute>b__0()
   at OpenQA.Selenium.Appium.AppiumWebElement.CacheValue(String key, Func`1 getter)
   at OpenQA.Selenium.Appium.AppiumWebElement.GetAttribute(String attributeName)

An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)

Please create a [gist](https://gist.github.com) with pasted stacktrace of exception thrown by .NET.

## Link to Appium logs
[JSONWP Proxy] Proxying [POST /wd/hub/session/dc4bfbbc-865d-4c5e-bb46-7fca085d37d2/execute] to [POST http://127.0.0.1:8002/wd/hub/session/f1a97960d66bdfa8163b650ac4910d3e/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[JSONWP Proxy] Got response with status 200: {"sessionId":"f1a97960d66bdfa8163b650ac4910d3e","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n  (Session info: chrome=69.0.3497.100)\n  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.15063 x86_64)"}}

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by MummanaSubramanya** [comment]
Getting the same exception https://github.com/appium/appium-dotnet-driver/issues/267.

**Comment by MummanaSubramanya** [comment]
@akinsolb : any update ?

**Comment by MummanaSubramanya** [comment]
Issue is closed but when i can expect a fixed version? 4.0.0.3 beta still has the issue

**Comment by MummanaSubramanya** [comment]
@KazuCocoa: when i can expect fixed version?

**Comment by KazuCocoa** [comment]
@akinsolb 
Do you have a chance to release a new version which has fixes of `getattribute` and `css convert` related?

**Comment by akinsolb** [comment]
@KazuCocoa @MummanaSubramanya Will make a beta release by the end of the day.

**Comment by MummanaSubramanya** [comment]
@akinsolb  @KazuCocoa  test still fails after updating to 4.0.0.4-beta. it still check for css selector after switching to native context.

Setup: android O, real device : Samausng galaxy 8, appium version 1.9.1, appium client: 4.0.0.4-beta

Below are my logs:

[HTTP] {"name":"NATIVE_APP"} [debug] [W3C] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","fee6cd95-0501-4416-9953-b444ee531624"] [debug] [AndroidDriver] Getting a list of available webviews [debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell cat /proc/net/unix' [debug] [AndroidDriver] WEBVIEW_30478 mapped to pid 30478 [debug] [AndroidDriver] Getting process name for webview [debug] [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s ce0718276bf16a2901 shell ps' [debug] [AndroidDriver] Parsed pid: '30478' pkg: 'com.essent.flix' from [debug] [AndroidDriver] USER PID PPID VSZ RSS WCHAN ADDR S NAME [debug] [AndroidDriver] u0_a207 30478 3401 3717200 453392 0 0 R com.essent.flix [debug] [AndroidDriver] Returning process name: 'com.essent.flix' [debug] [AndroidDriver] Found webviews: ["WEBVIEW_chrome","WEBVIEW_com.essent.flix"] [debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_chrome","WEBVIEW_com.essent.flix"] [debug] [W3C] Responding to client with driver.setContext() result: null [HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/context 200 394 ms - 14 [HTTP] [HTTP] --> POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element [HTTP] {"using":"css selector","value":"#com\\.android\\.packageinstaller\\:id\\/permission_allow_button"} [debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#com\\.android\\.packageinstaller\\:id\\/permission_allow_button","fee6cd95-0501-4416-9953-b444ee531624"] [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator [debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session [debug] [W3C] at AndroidUiautomator2Driver.validateLocatorStrategy (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:349:13) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:26:8) [debug] [W3C] at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40) [debug] [W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22) [debug] [W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37) [debug] [W3C] at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17) [debug] [W3C] at new Promise (<anonymous>) [debug] [W3C] at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36) [debug] [W3C] at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12) [debug] [W3C] at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0 [as findElOrElsWithProcessing] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:47:30) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:46:21) [debug] [W3C] at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40) [debug] [W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22) [debug] [W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at invoke (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37) [debug] [W3C] at enqueueResult (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:185:17) [debug] [W3C] at new Promise (<anonymous>) [debug] [W3C] at new F (C:\node_modules\appium\node_modules\core-js\library\modules\$.export.js:30:36) [debug] [W3C] at AsyncIterator.enqueue (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:184:12) [debug] [W3C] at AsyncIterator.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21) [debug] [W3C] at Object.runtime.async (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:209:12) [debug] [W3C] at AndroidUiautomator2Driver.callee$0$0 [as findElement] (C:\node_modules\appium\node_modules\appium-base-driver\build\lib\basedriver\commands\find.js:88:30) [debug] [W3C] at C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:296:26 [debug] [W3C] at tryCatcher (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23) [debug] [W3C] at Promise._settlePromiseFromHandler (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31) [debug] [W3C] at Promise._settlePromiseAt (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18) [debug] [W3C] at Promise._settlePromiseAtPostResolution (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10) [debug] [W3C] at Async._drainQueue (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12) [debug] [W3C] at Async._drainQueues (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10) [debug] [W3C] at Immediate.Async.drainQueues [as _onImmediate] (C:\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14) [debug] [W3C] at runCallback (timers.js:794:20) [debug] [W3C] at tryOnImmediate (timers.js:752:5) [debug] [W3C] at processImmediate [as _immediateCallback] (timers.js:729:5) [HTTP] <-- POST /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/element 400 66 ms - 4602 [HTTP] [HTTP] --> GET /wd/hub/session/fee6cd95-0501-4416-9953-b444ee531624/screenshot [HTTP] {}

**Comment by akinsolb** [comment]
@MummanaSubramanya Are you saying that calling the provided code example (above and below) throws the same error?

`IWebElement info = driver.FindElement(By.CssSelector("div[class='pnr-status'] span"));
string abc=info.GetAttribute("text");`

If so, can you provide the line of code, which contains your driver instantiation? otherwise raise a new. bug. My understanding of this bug is that

1. You are launching a hybrid app on android platform by:
`using new AppiumDriver<IWebDriver> = new AndroidDriver<IWebelement>(params)`
2. Switching to an available web context and then
3. Finding an IWebElement, and trying to access an attribute by:
`IWebElement info = driver.FindElement(By.CssSelector("div[class='pnr-status'] span"));
  string abc = info.GetAttribute("text");`

**Comment by MummanaSubramanya** [comment]
@akinsolb Here is my scenario
1) Launching the hybrid app with autoWebview=True
`using new AppiumDriver<AppiumWebElement> = new AndroidDriver<AppiumWebElement>(params)`
2) Then I perform some operations in the webview which creates an native alert.
3) To close the alert I switch to native view and then I try to click on the element `com.android.packageinstaller:id/permission_allow_button using By.ID`
4) When trying to click the element it check for css selector and it fails. 
Hope this clears

**Comment by akinsolb** [comment]
@MummanaSubramanya Right, you haven't provided the line of code used to search for the element, but I imagine it is as follows:
`driver.FindElement(By.Id("com.android.packageinstaller:id/permission_allow_button"));`

If so, can you try using a mobile FindByElement mechanism instead? like below:

`var element = driver.FindElementById("com.android.packageinstaller:id/permission_allow_button");`

**Comment by MummanaSubramanya** [comment]
@akinsolb : thanks `var element = driver.FindElementById("com.android.packageinstaller:id/permission_allow_button");` this worked in 1.9.1 but why is this weird behaviour ? I mean `driver.FindElement(By.Id("com.android.packageinstaller:id/permission_allow_button"));` works fine for me in 1.8.1?

**Comment by mykola-mokhnach** [comment]
This is because the obsolete automation backend is used. Android6+ wants Uiautomator2

**Comment by akinsolb** [comment]
Thanks @mykola-mokhnach

**Comment by KazuCocoa** [comment]
Because I fixed workaround by selenium in https://github.com/appium/appium-dotnet-driver/commit/ff78dd4e0b0a41131e17a2d30b1a5863d4f50f28#diff-b1bad8dd3d4b8d4314f4988822f4d371R259 . It is `driver.FindElementById`.
But I noticed dotnet driver has another method to call the workaround. It is `driver.FindElement(By.Id(`... in https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/By.cs
We should fix the workaround in `By` as well, probably. @MummanaSubramanya 

ah..

**Comment by MummanaSubramanya** [comment]
@KazuCocoa : any idea when you can fix it?

**Comment by akinsolb** [comment]
@MummanaSubramanya this issue has been fixed and is available to you via [NuGet - beta4](https://www.nuget.org/packages/Appium.WebDriver/4.0.0.4-beta). It will be released in Release 4.0. the method you should be using is `driver.FindElementById`

**Comment by MummanaSubramanya** [comment]
@akinsolb: `driver.FindElementById` works fine but the fix should also be working with By.id too which isnt working as expected.

**Comment by akinsolb** [comment]
@MummanaSubramanya  The By.Id mechanism is for web browsers, doesn't support mobile, and is therefore working as expected. If anything, there should be an Id property added to the MobileBy class, which you can raise as a separate issue for.

**Comment by MummanaSubramanya** [comment]
@akinsolb : As per you I tried with MobileBy.ID and it still looks for CSS selector.

`--> POST /wd/hub/session/11766b40-106f-4045-ae84-e5afe9727aea/element
[HTTP] {"using":"css selector","value":"#android\\:id\\/button1"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["css selector","#android\\:id\\/button1","11766b40-106f-4045-ae84-e5afe9727aea"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C]     at AndroidUiautomator2Driver.validateLocatorStrategy (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:349:13)
[debug] [W3C]     at AndroidUiautomator2Driver.callee$0$0$ (C:\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:26:8)
[debug] [W3C]     at tryCatch (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[debug] [W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[debug] [W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)`

**Comment by MummanaSubramanya** [comment]
Hmmm seems like I need to customize a bit to support  "driver.FindElementById" format thank you!!

**Comment by KazuCocoa** [comment]
Yes, we must override some methods in MobileBy

**Comment by akinsolb** [comment]
@KazuCocoa Will do this later today, to match appium's support for JSONWP

**Comment by PraveenNalla23** [comment]
Hi,
I am still facing the same issue with v4.0.0.4 and webdriver 3.14.0

Environment:
Appium server version or git revision if you use some shapshot: Appium Desktop v1.9.1
Desktop OS/version used to run Appium if necessary: Windows 10 Enterprise
Mobile platform/version under test: Android 8.0
Real device or emulator/simulator: Real Device Samsung Galaxy S3
IDE: VisualStudio 2017 Enterprise and C#
Appium WebDriver 4.0.0.4-beta
Selenium.WebDriver 3.14.0 same observation with 3.141.0 as well

Exception Details: 
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
  (Session info: chrome=70.0.3538.80)
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
   at VideoTile_Automation.Step_Definitions.AndroidTestSteps.GivenConnectionIsEstablished() in C:\Users\siddu\Desktop\Automation Versions\Automation_Nov06\WebClient_Automation\src\VideoTile_Automation\Step Definitions\AndroidTestSteps.cs:line 16


Appium Server Log:

[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to command name 'execute'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute' for MJSONWP protocol
[JSONWP Proxy] Proxying [POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute] to [POST http://127.0.0.1:8000/wd/hub/session/46b664738eea63271e3b22151ffe22de/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return\"string\"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||\"\";a=this.a.replace(/((?:^|\\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\\s\\xa0]+/g,\"\")});b=a.length-5;if(0>b||a.indexOf(\"Error\",b)!=b)a+=\"Error\";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||\"\"}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[JSONWP Proxy] Got response with status 200: {"sessionId":"46b664738eea63271e3b22151ffe22de","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n  (Session info: chrome=70.0.3538.80)\n  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)"}}
[W3C] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute has failed
[W3C]     at JWProxy.proxy$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[W3C]     at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C]     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
[W3C]     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C]     at 
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync 500 127 ms - 1933
[HTTP] 

Can you please check this asap. This issue is blocking my project automation.

Thanks,
Praveen

**Comment by PraveenNalla23** [comment]
> @KazuCocoa @MummanaSubramanya Will make a beta release by the end of the day.

Hi,
I am still facing the same issue with v4.0.0.4 and webdriver 3.14.0

Environment:
Appium server version or git revision if you use some shapshot: Appium Desktop v1.9.1
Desktop OS/version used to run Appium if necessary: Windows 10 Enterprise
Mobile platform/version under test: Android 8.0
Real device or emulator/simulator: Real Device Samsung Galaxy S3
IDE: VisualStudio 2017 Enterprise and C#
Appium WebDriver 4.0.0.4-beta
Selenium.WebDriver 3.14.0 same observation with 3.141.0 as well

Exception Details:
OpenQA.Selenium.WebDriverException
HResult=0x80131500
Message=An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
(Session info: chrome=70.0.3538.80)
(Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
Source=WebDriver
StackTrace:
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters) at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
at VideoTile_Automation.Step_Definitions.AndroidTestSteps.GivenConnectionIsEstablished() in C:\Users\siddu\Desktop\Automation Versions\Automation_Nov06\WebClient_Automation\src\VideoTile_Automation\Step Definitions\AndroidTestSteps.cs:line 16

Appium Server Log:

[W3C] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Matched '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to command name 'execute'
[Protocol Converter] Rewrote the original URL '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute' for MJSONWP protocol
[JSONWP Proxy] Proxying [POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute] to [POST http://127.0.0.1:8000/wd/hub/session/46b664738eea63271e3b22151ffe22de/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return"string"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
[JSONWP Proxy] Got response with status 200: {"sessionId":"46b664738eea63271e3b22151ffe22de","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n (Session info: chrome=70.0.3538.80)\n (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)"}}
[W3C] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute has failed
[W3C] at JWProxy.proxy$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
[W3C] at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
[W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
[W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js💯21)
[W3C] at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
[W3C] at
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync 500 127 ms - 1933
[HTTP]

Can you please check this asap. This issue is blocking my project automation.

Thanks,
Praveen

**Comment by PraveenNalla23** [comment]
> > @KazuCocoa @MummanaSubramanya Will make a beta release by the end of the day.
> 
> Hi,
> I am still facing the same issue with v4.0.0.4 and webdriver 3.14.0
> 
> Environment:
> Appium server version or git revision if you use some shapshot: Appium Desktop v1.9.1
> Desktop OS/version used to run Appium if necessary: Windows 10 Enterprise
> Mobile platform/version under test: Android 8.0
> Real device or emulator/simulator: Real Device Samsung Galaxy S3
> IDE: VisualStudio 2017 Enterprise and C#
> Appium WebDriver 4.0.0.4-beta
> Selenium.WebDriver 3.14.0 same observation with 3.141.0 as well
> 
> Exception Details:
> OpenQA.Selenium.WebDriverException
> HResult=0x80131500
> Message=An unknown server-side error occurred while processing the command. Original error: unknown error: a.getAttributeNode is not a function
> (Session info: chrome=70.0.3538.80)
> (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)
> Source=WebDriver
> StackTrace:
> at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
> at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters) at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary2 parameters)
> at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
> at VideoTile_Automation.Step_Definitions.AndroidTestSteps.GivenConnectionIsEstablished() in C:\Users\siddu\Desktop\Automation Versions\Automation_Nov06\WebClient_Automation\src\VideoTile_Automation\Step Definitions\AndroidTestSteps.cs:line 16
> 
> Appium Server Log:
> 
> [W3C] Driver proxy active, passing request on via HTTP proxy
> [JSONWP Proxy] Matched '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to command name 'execute'
> [Protocol Converter] Rewrote the original URL '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync' to '/wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute' for MJSONWP protocol
> [JSONWP Proxy] Proxying [POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute] to [POST http://127.0.0.1:8000/wd/hub/session/46b664738eea63271e3b22151ffe22de/execute] with body: {"script":"return (function(){return function(){var d=this;function f(a){return"string"==typeof a};function h(a,b){this.code=a;this.a=l[a]||m;this.message=b||"";a=this.a.replace(/((?:^|\s+)[a-z])/g,function(a){return a.toUpperCase().replace(/^[\s\xa0]+/g,"")});b=a.length-5;if(0>b||a.indexOf("Error",b)!=b)a+="Error";this.name=a;a=Error(this.message);a.name=this.name;this.stack=a.stack||""}\n(function(){var a=Error;function b(){}b.prototype=a.prototype;h.b=a.prototype;h.prototype=new b;h.prototype.constructor=h;h.a=function(b,c,g){for(var e=Array(arguments.length-2),k=2;k
> [JSONWP Proxy] Got response with status 200: {"sessionId":"46b664738eea63271e3b22151ffe22de","status":13,"value":{"message":"unknown error: a.getAttributeNode is not a function\n (Session info: chrome=70.0.3538.80)\n (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 10.0.17134 x86_64)"}}
> [W3C] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute has failed
> [W3C] at JWProxy.proxy$ (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:182:13)
> [W3C] at tryCatch (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
> [W3C] at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
> [W3C] at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js💯21)
> [W3C] at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
> [W3C] at
> [MJSONWP] Matched JSONWP error code 13 to UnknownError
> [HTTP] <-- POST /wd/hub/session/7249f3d4-ff1a-48a4-b0fb-2d87a3ebe6d4/execute/sync 500 127 ms - 1933
> [HTTP]
> 
> Can you please check this asap. This issue is blocking my project automation.
> 
> Thanks,
> Praveen

Forgot to mention that this issue is observed in android mobile web application.

Thanks,
Praveen

**Comment by MummanaSubramanya** [comment]
By.XXX and Mobile.XXX will fail in native view meanwhile you can use driver.fincelementbyid or driver.fincelementbyxpath

**Comment by KazuCocoa** [comment]
Could you share your test code?
Did you use AppiumWebElement like below sample code? 
https://github.com/appium/appium/blob/master/sample-code/csharp/test/TestAndroidCreateWebSession.cs

**Comment by PraveenNalla23** [comment]
@KazuCocoa, I WS using RemoteWebDriver instead of AndroidDriver. Working now after changing to Android Driver. Thanks.
