### ISSUE TITLE
Clicks are not working with Appium 1.3.5

### ISSUE THREAD

**Issue by lbielski** [appium/appium-dotnet-driver#81]
Hi!

Seems like clicks for IOS devices are not working with latest Appium version:  

`{"status":13,"value":"ERROR running Appium command: invalid json, empty body"}`  

Request is `/element/5003/click` with empty body.  

The same click works if I use Java client.  

Request is the same (`/element/5003/click`) but the body is not empty: `{"id":"5003"}`  

The client version is 1.2.0.8

**Comment by Astro03** [comment]
Wow.  Seems like a huge bug.  I'll fix it tomorrow and publish.  Thx.  

Ciao,
Astro
Sent from my phone

On Mar 4, 2015, at 02:17, lbielski <notifications@github.com> wrote:

Hi!

Seems like clicks for IOS devices are not working with latest Appium version:

{"status":13,"value":"ERROR running Appium command: invalid json, empty body"}

Request is /element/5003/click with empty body.

The same click works if I use Java client.

Request is the same (/element/5003/click) but the body is not empty: {"id":"5003"}

The client version is 1.2.0.8

**Comment by Astro03** [comment]
@lbielski - i just did a cursory look through, appium-dotnet-driver does not implement Click.  I believe the issue you are seeing resides with selenium.  Has this worked with previous versions of the dotnet driver?

**Comment by lbielski** [comment]
@Astro03 - one of our customers is using .Net driver and it works locally for him. Not sure about the Appium version he is running his tests against(I will ask him), but it seems like it used to work.

We also have implementation of the same test in Javascript (mocha and 'wd' client https://www.npmjs.com/package/wd) and clicks also work.

My guess would be that Appium changed json parsing in recent version/versions and selenium driver for .Net hasn't been updated. Are you using the latest version?

**Comment by Astro03** [comment]
I am not using the most up to date version of appium.  

If you can let me know the exact setup, I can delve into it more. 

Ciao,
Astro
Sent from my phone

On Mar 6, 2015, at 04:47, lbielski <notifications@github.com> wrote:

@Astro03 - one of our customers is using .Net driver and it works locally for him. Not sure about the Appium version he is running his tests against(I will ask him), but it seems like it used to work.

We also have implementation of the same test in Javascript (mocha and 'wd' client https://www.npmjs.com/package/wd) and clicks also work.

My guess would be that Appium changed json parsing in recent version/versions and selenium driver for .Net hasn't been updated. Are you using the latest version?

**Comment by rvanoord** [comment]
Hi!
I am using the latest version of the .Net Client which I downloaded via the Nuget package manager in Visual Studio 201.

Here is an except of the code I am using:

    var driver = new IOSDriver(new Uri("https://app.testobject.com:443/api/appium/wd/hub"), capabilities, new TimeSpan(0, 0, 15, 0, 0));
    driver.Context = "WEBVIEW";
    var loginView = driver.FindElementById("login-view");
    var username = loginView.FindElement(By.Id("username"));
    username.SendKeys("testuser");
    driver.GetScreenshot();
    var password = loginView.FindElement(By.Id("password"));
    password.SendKeys("Im leben");
    driver.GetScreenshot();
    var btn = loginView.FindElement(By.TagName("a")); //Element found
    btn.Click(); //FAILS
    driver.GetScreenshot();

RvO

**Comment by Astro03** [comment]
@penguinho is this what you were talking about? have you seen this problem?

**Comment by akinsolb** [comment]
Closing due to inactivity
